version: "2"
checks:
  method-lines:
    config:
      threshold: 40
  similar-code:
    enabled: false
  complex-logic:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10
plugins:
  tslint:
    enabled: true
  markdownlint:
    enabled: false
  csslint:
    enabled: true
exclude_patterns:
  # Backend File Specific Excludes
  # Frontend Pattern Excludes
  - "src/frontend/csrs-portal/karma.conf.js"
  - "src/frontend/csrs-portal/package.json"
  - "src/frontend/csrs-portal/tsconfig.json"
  - "src/frontend/csrs-portal/tslint.json"
  - "src/frontend/csrs-portal/**/*.spec.*"
  - "src/frontend/csrs-portal/**/*.model.*"
  - "src/frontend/csrs-portal/**/*.module.*"
  - "src/frontend/csrs-portal/**/*.routes.*"
  - "src/frontend/csrs-portal/**/abstract*.*"
  - "src/frontend/csrs-portal/shared/components/"
  - "src/frontend/*/src/*.spec.ts"
  - "src/frontend/*/src/*/*/*.spec.ts"
  - "src/frontend/*/src/*.component.ts"
  - "src/frontend/*/src/*/*/*.component.ts"
