version: "3.8"

services:
  # #############################################################################################
  # ###                                 Csrs FRONTEND                                         ###
  # #############################################################################################
  csrs-portal:
    container_name: csrs-portal
    build:
      context: ./src/frontend/csrs-portal
    restart: always
    ports:
      - "8080:8080"
    ## following is used for testing nginx.conf locally. No need to build the csrs-portal every
    ## time we change the nginx.conf
    #volumes:
    #  - ./src/frontend/csrs-portal/nginx.conf:/opt/app-root/etc/nginx.default.d/default.conf
  
  # #############################################################################################
  # ###                                 Csrs BACKEND                                          ###
  # #############################################################################################
  csrs-portal-api:
    container_name: csrs-portal-api
    build:
      context: ./src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "8081:8080"
  #############################################################################################
  ###                                  KEYCLOAK                                             ###
  #############################################################################################
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: http://localhost:5002/auth
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - 5002:8080

  # #############################################################################################
  # ###                                  KEYCLOAK CONFIG                                      ###
  # #############################################################################################
  keycloak-config:
    build:
      context: ./infrastructure/keycloak
      args:
        - KEYCLOAK_URL=http://keycloak:8080
    command: sh -c "dockerize -wait http://keycloak:8080 -timeout 300s /tmp/createuser.sh"
    depends_on: [keycloak]

  # #############################################################################################
  # ###                                  KEYCLOAK CONFIG                                      ###
  # #############################################################################################
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8041:80

networks:
  csrs-net:
    driver: "host"
