version: "3.8"

services:
  # #############################################################################################
  # ###                                 Csrs FRONTEND                                 ###
  # #############################################################################################
  csrs-portal:
    container_name: csrs-portal
    build:
      context: ./src/frontend/csrs-portal
    restart: always
    ports:
      - "8080:8080"
    ## following is used for testing nginx.conf locally. No need to build the csrs-portal every
    ## time we change the nginx.conf
    #volumes:
    #  - ./src/frontend/csrs-portal/nginx.conf:/opt/app-root/etc/nginx.default.d/default.conf
