apiVersion: tekton.dev/v1beta1
# Push this from GitHub Actions to OpenShift as SecOps wants private site to be scanned
# Too
# Adjuting the GitHub Action Equivalent one to work with Private repo
# Would either need writing custom actions or self hosted OpenShift Runner
# That route did not go smoothly yet; hence took the Tekton route
# Have to add nice html report options and scheduled execution

kind: Pipeline

  name: scan-pipeline
  namespace: blahblahlicenseplate-tools

spec:
  params:
    - default: jag-csrs
      name: APPLICATION_NAME
      type: string
    - default: jag-csrs
      name: ''
      type: string
  tasks:
    - name: pentesting-dev
      params:
        - name: APP_URL
          value: 'blahblah dev url'
        - name: WORK_DIRECTORY
          value: $(params.APPLICATION_NAME)/dev
      taskRef:
        kind: Task
        name: zap-proxy
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: pentesting-test
      params:
        - name: APP_URL
          value: 'blahblah test url'
        - name: WORK_DIRECTORY
          value: $(params.APPLICATION_NAME)/test
      taskRef:
        kind: Task
        name: zap-proxy
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: pentesting-prod
      params:
        - name: APP_URL
          value: 'blahblah prod url'
        - name: WORK_DIRECTORY
          value: $(params.APPLICATION_NAME)/prod
      taskRef:
        kind: Task
        name: zap-proxy
      workspaces:
        - name: output
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: true