kind: Template
apiVersion: v1
metadata:
  name: csrs-file-manager-ca-template
  description: csrs-file-manager-ca-template


objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: csrs-file-manager-ca
    annotations:
      service.beta.openshift.io/inject-cabundle: "true"
      app.kubernetes.io/part-of: jag-csrs-file-manager