kind: Template
apiVersion: v1
metadata:
  name: app.config.json  template
  description: Angular app config template 


parameters:

- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: false
  # Below value must be changed as per gold cluster oc nameplate
  value: licenseplate

- name: OC_ENV
  description: The OpenShift environment, ie dev, test or prod
  required: true
  

objects:

- kind: ConfigMap
  apiVersion: v1

  metadata:
    name: frontend-app-config
    namespace: ${OC_NAMESPACE}-${OC_ENV}

  data:
    app.config.json: |
      { "production": false,

      "environment": "dev",

      "version": "1.0.0",

      "cscLink":
      "https://www2.gov.bc.ca/gov/content/life-events/divorce/family-justice/who-can-help/recalculate-child-support-csrs",

      "bceIdRegisterLink":
      "https://www.test.bceid.ca/register/basic/account_details.aspx?type=regular&eServiceType=basic",

      "bceIdRegisterLink_P":
      "https://www.bceid.ca/register/basic/account_details.aspx?type=regular&eServiceType=basic",

      "downloadApplication":
      "https://www2.gov.bc.ca/assets/gov/birth-adoption-death-marriage-and-divorce/divorce/family/basics/help/child-support-recalculation-service/csrs-application.pdf"
      }
