kind: Template
apiVersion: v1
metadata:
  name: app.config.json  template
  description: Angular app config template 


parameters:

- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: true

- name: OC_ENV
  description: The OpenShift environment, ie dev, test or prod
  required: true
  

objects:

- kind: ConfigMap
  apiVersion: v1

  metadata:
    name: frontend-app-config
    namespace: ${OC_NAMESPACE}-${OC_ENV}

  data:
    app.config.json: |
      { "production": false,

      "environment": "dev",

      "version": "1.0.0",

      "cscLink":
      "https://www2.gov.bc.ca/gov/content?id=6C3AEB40190744B0BDC21C3932C3891B",

      "bceIdRegisterLink":
      "https://www.test.bceid.ca/register/basic/account_details.aspx?type=regular&eServiceType=basic",

      "bceIdRegisterLink_P":
      "https://www.bceid.ca/register/basic/account_details.aspx?type=regular&eServiceType=basic",

      "downloadApplication":
      "https://www2.gov.bc.ca/assets/download/47F793A14BB045B882329717D9BFB706"
      }
