apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: api-image-stream-template
  description: image stream template for the JAG-csrs api
  
parameters:
- name: COMPONENT_NAME
  description: The API component name
  required: true
  value: jag-csrs-api
  
- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: true
  # Below value must be changed as per gold cluster oc nameplate
  value: blahblah


objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream

  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}-dev
  spec:
    lookupPolicy:
      local: false
