apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: frontend-image-stream-template
  description: image stream template for the JAG-csrs frontend
  
parameters:

- name: COMPONENT_NAME
  description: The API component name
  required: true
  value: jag-csrs-frontend
  
- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: true
  # Below value must be changed as per gold cluster oc nameplate
  value: blahblah

  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}
  spec:
    lookupPolicy:
      local: false