kind: Template
apiVersion: v1
metadata:
  name: oidc-config-template
  description: oidc-config-template


parameters:

- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: true


- name: OC_ENV
  description: The OpenShift environment, ie dev, test or prod
  required: true
  

objects:

- kind: ConfigMap
  apiVersion: v1

  metadata:
    name: oidc-config
    namespace: ${OC_NAMESPACE}-${OC_ENV}

  data:
    oidc.json: |

    { "postLoginRoute": "/welcomeuser",
      "authority": "https://dev.loginproxy.gov.bc.ca/auth/realms/standard",
      "redirectUrl": "https://dev.childsupportrecalc.gov.bc.ca",
      "postLogoutRedirectUri": "https://dev.childsupportrecalc.gov.bc.ca",
      "clientId": "jsb-csrs-4126", "kc_idp_hint": "bceid-basic", 
      "scope": "openid profile",
      "responseType": "code",
      "prompt": "consent"
    } 