name: Trivy Scan
on:
  schedule:
    # Experimental schedule;
    # 9:15 pm PST Tuesday ---> 5:15 AM UTC Wednesday
    - cron:  '15 05 * * 3'
  workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Openshift using OC SA and Token of respective env.
      - name: Authenticate OC Env Specific SA
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools
          OPENSHIFT_USER: ${{secrets.OPENSHIFT_DEPLOYER_SA_USERNAME}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_DEPLOYER_SA_PASSWORD}}
          namespace: ${OPENSHIFT_NAMESPACE}

      - name: Run Trivy vulnerability scanner on frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/jag-csrs-frontend:dev'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{secrets.OPENSHIFT_DEPLOYER_SA_USERNAME}}
          TRIVY_PASSWORD: ${{secrets.OPENSHIFT_DEPLOYER_SA_PASSWORD}} 

