# https://github.com/marketplace/actions/openshift-self-hosted-runner-installer
# https://developers.redhat.com/articles/2021/06/16/deploy-self-hosted-github-actions-runners-red-hat-openshift
name: Trivy Scan
on:
  schedule:
  #  # Experimental schedule;
  #  # 9:15 pm PST Tuesday ---> 5:15 AM UTC Wednesday
    - cron:  '15 05 * * 3'
  push:
    branches:
      improving_infra_v2
  workflow_dispatch:
jobs:
  install_runner:
    name: Install Runner
    runs-on: ubuntu-20.04
    environment:
    steps:
      # Login to Openshift using OC SA and Token of respective env.
      - name: Authenticate OC Env Specific SA
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools
          username: ${{secrets.OPENSHIFT_BUILDER_SA_USERNAME_TOOLs}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_BUILDER_SA_PASSWORD_TOOLS}}
          namespace: ${OPENSHIFT_NAMESPACE}

      - name: self hosted runner installer
        uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.TOKEN_SELF_HOSTED_RUNNER }}
  self-hosted-workflow:
    runs-on : [self-hosted]
    needs: install_runner
    steps:
      - name: Run Trivy vulnerability scanner on frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/jag-csrs-frontend:test'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{secrets.OPENSHIFT_BUILDER_SA_USERNAME_TOOLs}}
          TRIVY_PASSWORD: ${{secrets.OPENSHIFT_BUILDER_SA_PASSWORD_TOOLS}}
      - name: Upload frontend Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
