name: CSRS API

on:
  push:
  pull_request:
    paths:
      - 'src/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Build Api
        run: dotnet build
        working-directory: ./src/backend/Csrs.Api
      - name: Test Api
        run: dotnet test
        working-directory: ./src/backend/Csrs.Test
