name: ZAP Scan (TEST) on Demand
on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'https://test.childsupportrecalc.gov.bc.ca/'
          token: ${{ secrets.GITHUB_TOKEN }}
