name: ZAP Scan
on:
  schedule:
    # Experimental schedule;
    # HAve to be mindful of load on shared system
    - cron:  '25 07 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'https://dev.childsupportrecalc.gov.bc.ca/'
          token: ${{ secrets.GITHUB_TOKEN }}
